server:
  port: 4002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/orders_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

user:
  service:
    url: http://localhost:4000